language: node_js
node_js:
  - 12

branches:
  only:
    - /^(v([0-9]+|x).([0-9]+|x).([0-9]+|x))$/

jobs:
  include:
    - stage: Build and release
      before_script:
        - npm run test
      script:
        - npm run build
      after_success:
        - npm run release
